export const START_FETCH_CHARACTERS = 'START_FETCH_CHARACTERS';
export const SUCCESS_FETCH_CHARACTERS = 'SUCCESS_FETCH_CHARACTERS';
export const ERROR_FETCH_CHARACTERS = 'ERROR_FETCH_CHARACTERS';

export const START_FETCH_CHARACTER_DETAILS = 'START_FETCH_CHARACTER_DETAILS';
export const SUCCESS_FETCH_CHARACTER_DETAILS =
	'SUCCESS_FETCH_CHARACTER_DETAILS';
export const ERROR_FETCH_CHARACTER_DETAILS = 'ERROR_FETCH_CHARACTER_DETAILS';

export const START_FETCH_FILMS = 'START_FETCH_FILMS';
export const SUCCESS_FETCH_FILMS = 'SUCCESS_FETCH_FILMS';
export const ERROR_FETCH_FILMS = 'ERROR_FETCH_FILMS';
